spring:
  datasource:
#    url: jdbc:h2:mem:mydb in memory
    url: jdbc:h2:./src/main/resources/data/demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 123
    driverClassName: org.h2.Driver
    h2:
      console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true



